/* Generated By:JJTree: Do not edit this line. ASTBlockStatements.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser;

public
class ASTBlockStatements extends SimpleNode {
  public ASTBlockStatements(int id) {
    super(id);
  }

  public ASTBlockStatements(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b67d85eb9e49f7c060d83d530f56a43 (do not edit this line) */
