/* Generated By:JJTree: Do not edit this line. ASTCommentStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser;

public
class ASTCommentStatement extends SimpleNode {
  public ASTCommentStatement(int id) {
    super(id);
  }

  public ASTCommentStatement(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0b5a2c5168517db06880e271182c2a86 (do not edit this line) */
