/* Generated By:JJTree: Do not edit this line. ASTFunctionParameterList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser;

public
class ASTFunctionParameterList extends SimpleNode {
  public ASTFunctionParameterList(int id) {
    super(id);
  }

  public ASTFunctionParameterList(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1042b3f17f0946c4a315378959afd407 (do not edit this line) */
