/* Generated By:JJTree: Do not edit this line. ASTFunctionInvoke.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser;

public
class ASTFunctionInvoke extends SimpleNode {
  public ASTFunctionInvoke(int id) {
    super(id);
  }

  public ASTFunctionInvoke(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2a70700590ea6c5b54cadefc70f2a88b (do not edit this line) */
