/* Generated By:JJTree: Do not edit this line. ASTFunctionDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser;

public
class ASTFunctionDeclarator extends SimpleNode {
  public ASTFunctionDeclarator(int id) {
    super(id);
  }

  public ASTFunctionDeclarator(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1f91dd568a951e4705fcabd8a14a426c (do not edit this line) */
