/* Generated By:JJTree: Do not edit this line. ASTPrimary2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser;

public
class ASTPrimary2 extends SimpleNode {
  public ASTPrimary2(int id) {
    super(id);
  }

  public ASTPrimary2(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5dfe332802fe8b8e63722f8c71557d3f (do not edit this line) */
