/* Generated By:JJTree: Do not edit this line. ASTPostIncDecExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser;

public
class ASTPostIncDecExpression extends SimpleNode {
  public ASTPostIncDecExpression(int id) {
    super(id);
  }

  public ASTPostIncDecExpression(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f87c8e3da11360e8b2b5655aea346462 (do not edit this line) */
