/* Generated By:JJTree: Do not edit this line. ASTSimpleUnaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser;

public
class ASTSimpleUnaryExpression extends SimpleNode {
  public ASTSimpleUnaryExpression(int id) {
    super(id);
  }

  public ASTSimpleUnaryExpression(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=13b995db574323148590a843595294e1 (do not edit this line) */
