/* Generated By:JJTree: Do not edit this line. ASTSimpleStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser;

public
class ASTSimpleStatement extends SimpleNode {
  public ASTSimpleStatement(int id) {
    super(id);
  }

  public ASTSimpleStatement(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=589c716d6d693c73cadc169b55e58ba5 (do not edit this line) */
