/* Generated By:JJTree: Do not edit this line. ASTStructBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser;

public
class ASTStructBody extends SimpleNode {
  public ASTStructBody(int id) {
    super(id);
  }

  public ASTStructBody(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e847c47cfa200656012f7a07b956c342 (do not edit this line) */
