/* Generated By:JJTree: Do not edit this line. ASTStructParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser;

public
class ASTStructParameter extends SimpleNode {
  public ASTStructParameter(int id) {
    super(id);
  }

  public ASTStructParameter(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9816a45a15c3af2ce68b3fa587f9774d (do not edit this line) */
