/* Generated By:JJTree: Do not edit this line. ASTStructDeclarations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser;

public
class ASTStructDeclarations extends SimpleNode {
  public ASTStructDeclarations(int id) {
    super(id);
  }

  public ASTStructDeclarations(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=80c46621e75d176788f1591cc0351282 (do not edit this line) */
