/* Generated By:JavaCC: Do not edit this line. Eg2TreeConstants.java Version 5.0 */
package Parser;

public interface Eg2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTARRAYINITIALIZER = 1;
  public int JJTUNIVERSALDECLARATOR = 2;
  public int JJTSTRUCTDECLARATION = 3;
  public int JJTSTRUCTBODY = 4;
  public int JJTSTRUCTDECLARATIONS = 5;
  public int JJTSTRUCTPARAMETER = 6;
  public int JJTFUNCTIONDECLARATOR = 7;
  public int JJTFUNCTIONPARAMETERLIST = 8;
  public int JJTFUNCTIONPARAMETER = 9;
  public int JJTFUNCTIONBODY = 10;
  public int JJTBLOCK = 11;
  public int JJTBLOCKSTATEMENTS = 12;
  public int JJTBLOCKSTATEMENT = 13;
  public int JJTSTATEMENT = 14;
  public int JJTSIMPLESTATEMENT = 15;
  public int JJTEMPTYSTATEMENT = 16;
  public int JJTIFSTATEMENT = 17;
  public int JJTWHILESTATEMENT = 18;
  public int JJTFORSTATEMENT = 19;
  public int JJTFOREACHSTATEMENT = 20;
  public int JJTBREAKSTATEMENT = 21;
  public int JJTCONTINUESTATEMENT = 22;
  public int JJTRETURNSTATEMENT = 23;
  public int JJTCOMMENTSTATEMENT = 24;
  public int JJTEXPRESSION = 25;
  public int JJTASSIGNMENTEXPRESSION = 26;
  public int JJTCONDITIONALEXPRESSION = 27;
  public int JJTCONDITIONALOREXPRESSION = 28;
  public int JJTCONDITIONALANDEXPRESSION = 29;
  public int JJTINCLUSIVEOREXPRESSION = 30;
  public int JJTEXCLUSIVEOREXPRESSION = 31;
  public int JJTANDEXPRESSION = 32;
  public int JJTEQUALITYEXPRESSION = 33;
  public int JJTRELATIONALEXPRESSION = 34;
  public int JJTSHIFTEXPRESSION = 35;
  public int JJTADDITIVEEXPRESSION = 36;
  public int JJTADD = 37;
  public int JJTMULTIPLICATIVEEXPRESSION = 38;
  public int JJTMULT = 39;
  public int JJTUNARYEXPRESSION = 40;
  public int JJTPREINCDECEXPRESSION = 41;
  public int JJTPOSTINCDECEXPRESSION = 42;
  public int JJTSIMPLEUNARYEXPRESSION = 43;
  public int JJTPRIMARY = 44;
  public int JJTFUNCTIONINVOKE = 45;
  public int JJTPRIMARY2 = 46;
  public int JJTLEFTSIDE = 47;
  public int JJTMYID = 48;


  public String[] jjtNodeName = {
    "Start",
    "ArrayInitializer",
    "UniversalDeclarator",
    "StructDeclaration",
    "StructBody",
    "StructDeclarations",
    "StructParameter",
    "FunctionDeclarator",
    "FunctionParameterList",
    "FunctionParameter",
    "FunctionBody",
    "Block",
    "BlockStatements",
    "BlockStatement",
    "Statement",
    "SimpleStatement",
    "EmptyStatement",
    "IfStatement",
    "WhileStatement",
    "ForStatement",
    "ForeachStatement",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "CommentStatement",
    "Expression",
    "AssignmentExpression",
    "ConditionalExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "InclusiveOrExpression",
    "ExclusiveOrExpression",
    "AndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "Add",
    "MultiplicativeExpression",
    "Mult",
    "UnaryExpression",
    "PreIncDecExpression",
    "PostIncDecExpression",
    "SimpleUnaryExpression",
    "Primary",
    "FunctionInvoke",
    "Primary2",
    "LeftSide",
    "MyID",
  };
}
/* JavaCC - OriginalChecksum=2a76d15b5a7ae216a8f77badce9f0541 (do not edit this line) */
