/* Generated By:JJTree: Do not edit this line. ASTArrayDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayDeclarator extends SimpleNode {
  public ASTArrayDeclarator(int id) {
    super(id);
  }

  public ASTArrayDeclarator(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a37d2a93e062f0bc6544cdf76b1dc76b (do not edit this line) */
