/* Generated By:JJTree: Do not edit this line. ASTArrayInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayInitializer extends SimpleNode {
  public ASTArrayInitializer(int id) {
    super(id);
  }

  public ASTArrayInitializer(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=735406ac9da74b68abc322ed46bd2105 (do not edit this line) */
