/* Generated By:JJTree: Do not edit this line. ASTBlockStatements.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBlockStatements extends SimpleNode {
  public ASTBlockStatements(int id) {
    super(id);
  }

  public ASTBlockStatements(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bd24854e73f2fd7603ca701e4b02eda2 (do not edit this line) */
