/* Generated By:JJTree: Do not edit this line. ASTDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclarator extends SimpleNode {
  public ASTDeclarator(int id) {
    super(id);
  }

  public ASTDeclarator(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b89872c3010368c9e8a6b299b7c2bd51 (do not edit this line) */
