/* Generated By:JJTree: Do not edit this line. ASTFunctionInvoke.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionInvoke extends SimpleNode {
  public ASTFunctionInvoke(int id) {
    super(id);
  }

  public ASTFunctionInvoke(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d5c5e1d40d50cd59db42ef0cb1c31e28 (do not edit this line) */
