/* Generated By:JJTree: Do not edit this line. ASTFunctionParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionParameter extends SimpleNode {
  public ASTFunctionParameter(int id) {
    super(id);
  }

  public ASTFunctionParameter(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9f00f959bf755192a77d036c9850a069 (do not edit this line) */
