/* Generated By:JJTree: Do not edit this line. ASTFunctionDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionDeclarator extends SimpleNode {
  public ASTFunctionDeclarator(int id) {
    super(id);
  }

  public ASTFunctionDeclarator(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b884f74a5569b3164a90a1caa2601aaf (do not edit this line) */
