/* Generated By:JJTree: Do not edit this line. ASTForeachStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTForeachStatement extends SimpleNode {
  public ASTForeachStatement(int id) {
    super(id);
  }

  public ASTForeachStatement(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8676ca7c553a6345900727cd9852b6f8 (do not edit this line) */
