/* Generated By:JJTree: Do not edit this line. ASTInclusiveOrExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInclusiveOrExpression extends SimpleNode {
  public ASTInclusiveOrExpression(int id) {
    super(id);
  }

  public ASTInclusiveOrExpression(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a650e89272425b40001da1d406063515 (do not edit this line) */
