/* Generated By:JJTree: Do not edit this line. ASTPreIncDecExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPreIncDecExpression extends SimpleNode {
  public ASTPreIncDecExpression(int id) {
    super(id);
  }

  public ASTPreIncDecExpression(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1583d2b52d0032e30e200564a324b49f (do not edit this line) */
