/* Generated By:JJTree: Do not edit this line. ASTPointor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPointor extends SimpleNode {
  public ASTPointor(int id) {
    super(id);
  }

  public ASTPointor(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5c59533eea2e5d23d290fb8276bea7d6 (do not edit this line) */
