/* Generated By:JJTree: Do not edit this line. ASTStructBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStructBody extends SimpleNode {
  public ASTStructBody(int id) {
    super(id);
  }

  public ASTStructBody(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=49fb9ce4fe17974de360cb1380a29f12 (do not edit this line) */
