/* Generated By:JJTree: Do not edit this line. ASTStructDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStructDeclaration extends SimpleNode {
  public ASTStructDeclaration(int id) {
    super(id);
  }

  public ASTStructDeclaration(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=27e88df99cc3aef89f6a8d600525c104 (do not edit this line) */
