/* Generated By:JJTree: Do not edit this line. ASTUniversalDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTUniversalDeclarator extends SimpleNode {
  public ASTUniversalDeclarator(int id) {
    super(id);
  }

  public ASTUniversalDeclarator(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=78aafaea9173c49b47f52f9cd8891a71 (do not edit this line) */
